- id:     multi
  orders:
    - id:     1
      side:   sell
      volume: 0.02
      price:  2.07
    - id:     2
      side:   sell
      volume: 0.03
      price:  2.06
    - id:     3
      side:   sell
      volume: 0.01
      price:  1.9
    - id:     4
      side:   buy
      volume: 0.01
      price:  1.83
    - id:     5
      side:   buy
      volume: 0.01
      price:  1.85
    - id:     6
      side:   buy
      volume: 0.01
      price:  1.95
    - id:     7
      side:   buy
      volume: 0.01
      price:  1.80
    - id:     8
      side:   buy
      volume: 0.01
      price:  2.01
    - id:     9
      side:   buy
      volume: 0.01
      price:  1.7
    - id:     10
      side:   buy
      volume: 0.01
      price:  1.83
- id:     buy
  order: 
    side:   buy
    volume: 0.02
    price:  2.05
- id:     sell
  order:
    side:   sell
    volume: 0.02
    price:  1.83